### ISSUE TITLE
[Code structure] Config options for experimentation

### ISSUE THREAD

**Issue by microbit-matt-hillsdon** [microbit-foundation/python-editor-next#207]
We've agreed to add a bunch of configuration options to make the code structure highlighting option more configurable.

We'll also add and/or document some CSS variables to enable easy experimenting with the colours used.

- [x] As a first step we should collapse the separate implementations. The l-shaped-boxes one should have all the information needed to draw the others. When we went with separate implementations the expectation was that we were going to make a quick choice but that seems less likely now.
- [x] Add functional options documented in Paper doc to settings
- [x] Add colour options
- [x] Document options for initial Foundation feedback
- [x] Revise/merge

**Comment by microbit-matt-hillsdon** [comment]
This will probably also fix #204 or at least make it trivial.

**Comment by microbit-matt-hillsdon** [comment]
Borders and l-shapes are a problematic combo if we stick with rounded corners

![image](https://user-images.githubusercontent.com/44397098/126797450-9f7c94cd-4905-49d8-b1d3-626cbc445eeb.png)

We might be able to make it work with an SVG but that would require a degree of reworking. Would probably let you round the inner corner of the L though.

**Comment by microbit-matt-hillsdon** [comment]
Hard to say whether this left-edge-only boxes background combo is a good thing either:

![image](https://user-images.githubusercontent.com/44397098/126798242-104cc9af-5b52-47a3-a2b0-6a38e5b4da2f.png)

**Comment by microbit-matt-hillsdon** [comment]
We can't use CSS for hover in a straightforward way as L-shapes are made up of multiple boxes. I guess we might as well use event listeners for both cases for now, potentially simplifying in future.

**Comment by microbit-matt-hillsdon** [comment]
I'll leave this on a branch for an initial round of feedback.

The most significant change for someone who doesn't engage with the options is stopping trimming trailing whitespace from the scope of a block. We could reinstate that but then I think it would be critical that we didn't highlight when we were in that whitespace as the mismatch is jarring.

**Comment by jaustin** [comment]
Playing with the settings on the latest branch made https://review-python-editor-next.microbit.org/code-structure-settings-jonny/ I've realised a couple of things

The approach I took where I made the 'selected block' darker than the block background kinda limits (a) how strong the main block background colours can be and (b) means that we get into contrast issues sooner. For example it's harder to see the structure highlighting of the deeper nested bits of code once you've selected a lightly nested block...

I accidentally revisited the branch where Matt had made the selected block yellow, and I think there's a real advantage to the extra brightness you get from this.

Here are some examples of some options, the first is the existing proposal,  then a yellow, then a magenta option.
The yellow is a bit crunchy against the overall editor palette for me. The purple is better but I worry about contrast on some of the keyword highlighting.

![subtle colours](https://user-images.githubusercontent.com/147113/129938133-b8675c16-304b-4c13-a648-223da1b3dd33.gif)
![unsubtle colours](https://user-images.githubusercontent.com/147113/129938151-8cdcfea7-97ea-4929-a26b-bd907312bdd8.gif)
![purple w border colours](https://user-images.githubusercontent.com/147113/129938170-0ac3f455-1395-4580-ad48-99dc2ce3b06d.gif)
![magenta w border colours](https://user-images.githubusercontent.com/147113/129938322-3d834fe6-78d7-4ce4-a320-064c3b61236a.gif)

**Comment by microbit-matt-hillsdon** [comment]
All on :root (view from html element in dev tools):

--chakra-colors-code-blockBorder: rgba(123, 205, 194, 0.1);
--chakra-colors-code-blockBackground: rgba(123, 205, 194, 0.1);
--chakra-colors-code-blockBackgroundActive: lightyellow;
--chakra-colors-code-blockBorderActive: #262626;
