### ISSUE TITLE
[Code structure] Full highlight doesn't update after horizontal scroll 

### ISSUE THREAD

**Issue by martinwork** [microbit-foundation/python-editor-next#253]
## Bug Description

Full code structure highlight doesn't update after horizontal scroll 

## How To Reproduce

1. Go to 'https://python.microbit.org/v/alpha'
2. Make the browser window narrower
3. Scroll across

## Expected behavior

The shaded are should update

## Screenshots

![image](https://user-images.githubusercontent.com/989126/130783758-f921318b-c849-4a87-b0bb-19bbdc758587.png)

## Environment

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome

**Smartphone (please complete the following information):**

**Comment by JohnVidler** [comment]
Depth markers get weird with this too at deep depths:
![Screenshot2022_04_26_113937](https://user-images.githubusercontent.com/537325/165284745-24eec051-cf0e-492c-8f66-d771ba3dbb77.jpg)
![Screenshot2022_04_26_114210](https://user-images.githubusercontent.com/537325/165284750-8554bddf-806b-4b67-b589-d9f16dfb541a.jpg)

**Comment by microbit-matt-hillsdon** [comment]
The original issue has a work-in-progress fix on #752.

I expected it to fix https://github.com/microbit-foundation/python-editor-next/issues/253#issuecomment-1109649384 too but that one seems stranger. You can repro it with a narrow window and much less content. It happens to the first block that overflows the width of the window (and so requires scrolling).

**Comment by microbit-matt-hillsdon** [comment]
The second issue on this ticket appears to be unrelated to code structure highlighting.

![image](https://user-images.githubusercontent.com/44397098/170531337-f8601161-13f8-4d26-b05a-c93b5b8bc3ac.png)

If you look carefully the line indicator also stops short. The content editable is not growing in this circumstance which seems likely to cause other bugs. The text still looks ok as it overflows. I'll see if I can reproduce it in a more minimal setup.

**Comment by microbit-matt-hillsdon** [comment]
Raised https://github.com/microbit-foundation/python-editor-next/issues/753 for the editor size/scroll issue.
