### ISSUE TITLE
Flashing: explain to user that first flash takes a longer time

### ISSUE THREAD

**Issue by jaustin** [microbit-foundation/python-editor-next#254]
## Description

In the current live editor, we explain to the user that the first flash takes a longer time than subsequent flashes.

This is reassuring, given that the first flash can take a long time for slower machines
![Screenshot2021_08_26_174957](https://user-images.githubusercontent.com/147113/131004591-85310ff2-1e41-4594-91dd-bc386f8685e0.jpg)

## Todo

- [ ] Choose whether to lift message as is (I'm happy with that)
- [ ] Implement

**Comment by microbit-matt-hillsdon** [comment]
Full flash dialog:

![image](https://user-images.githubusercontent.com/44397098/132185841-4bead523-e375-46a5-b064-c27acc575e3a.png)
