### ISSUE TITLE
[Toolkits] DnD from Reference and Explore toolkits

### ISSUE THREAD

**Issue by microbit-matt-hillsdon** [microbit-foundation/python-editor-next#335]
Implement DnD from the Reference and Explore toolkits into the code editor.

- On hover drag handles on the code snippets in Explore and the signature in Reference (tablet to be considered later, might require more changes).
- "Ghost code" in the editor, similar to previous spike.
- Drop behaviour as per the apidocs-dnd branch for Reference drags. For Explore, just insert and move caret to the end.
- Show imports on drag? They're fixed regardless of where you drop could be clearer.

Desirable but later:
- Drop into the REPL. Does that affect showing imports on drag? Does it send Ctrl-C, then paste with paste mode.

For discussion after:
- Insert into REPL button when connected via WebUSB. Perhaps "Run" or "Try it" ?

**Comment by microbit-matt-hillsdon** [comment]
For the ghost code, I think we can make edits to the document annotating the transaction with the `Transaction.addToHistory.of(false)` annotation. 

This is done the collab module which has a similar problem of edits from two sources. So long as we take responsibility for undoing our changes we'll be fine. We're playing on easy mode compared to collab as we know no other changes can happen during the drag operation.

**Comment by microbit-robert** [comment]
Possible future improvement:

- When dragging and dropping a code snippet into an area that should be a code block (i.e., underneath `while True:` or something similar), this code snippet should be indented to proper level, instead of falling back to the base line (no indentation).
