### ISSUE TITLE
Serial console scrollbar not draggable with mouse

### ISSUE THREAD

**Issue by microbit-giles** [microbit-foundation/python-editor-next#380]
## Bug Description

I can't drag the scrollbar in the serial console by clicking on it and dragging it with the mouse.

## How To Reproduce

Steps to reproduce the behaviour:
1. Go to https://python.microbit.org/v/alpha
2. Plug in micro:bit  
3. Click on Connect
4. Click 'Show serial'
5. Interact with serial console several times
6. Click and hold serial console scrollbar with mouse
7. Try to scroll serial console with mouse pointer

## Expected behaviour

Expect scrollbar to move when you click and drag it

## Environment

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome 
 - Version 96.0.4664.55 (Official Build) (arm64)

**Comment by microbit-matt-hillsdon** [comment]
As mentioned elsewhere, I can drag the scrollbar in the same terminal component in VS Code so we should see if there’s anything we’ve done that’s broken this.

Looks likely that this is the cause: https://github.com/xtermjs/xterm.js/issues/2757

We enable the accessibility mode unconditionally.
