### ISSUE TITLE
[Toolkits] Design of 'introduction' for each entry needs updating

### ISSUE THREAD

**Issue by microbit-robert** [microbit-foundation/python-editor-next#421]
After the changes made in #400, we used the topic title and subtitle in the second level breadcrumb, rather than topic title and introduction as these are very variable in length and can be quite long. The introduction currently sits below the breadcrumb in the toolkit scrollable area (see example below), however, this is not catered for in the designs. Need discussion to resolve.

![image](https://user-images.githubusercontent.com/95928279/149125610-5a3f7555-3b40-42af-bb9f-0f54e708f32c.png)

**Comment by microbit-matt-hillsdon** [comment]
We're not sure this looks bad and don't have a plan to improve. Closing.
