### ISSUE TITLE
Investigate text drag-and-drop

### ISSUE THREAD

**Issue by microbit-matt-hillsdon** [microbit-foundation/python-editor-next#449]
Something is wrong with text drag and drop, perhaps due to our own drag and drop handling.

If you drag code you can make it disappear.

Highlight like this and drag from the indent area. Sometimes it breaks, sometimes it doesn't drag at all.

![image](https://user-images.githubusercontent.com/44397098/150374920-04a47316-0eb2-4dc2-9b7e-2952d4b8034a.png)

**Comment by microbit-robert** [comment]
#581 fixes the issue of text disappearing on drag, however, no cursor is shown when dragging text inside the editor, so it is hard to pin point exactly where the text will drop. `@codemirror/view@0.19.31` introduces the `dropCursor` extension which fixes this issue. We should add this to the CodeMirror config when we have upgrade CodeMirror to the latest version.
