### ISSUE TITLE
Make “my program” a translatable string?

### ISSUE THREAD

**Issue by microbit-matt-hillsdon** [microbit-foundation/python-editor-next#450]
One for discussion. It's currently stored along with the initial program which isn't localised.

![image](https://user-images.githubusercontent.com/44397098/152179907-71cd5040-c8f8-4fa3-b80d-961f23bde222.png)

**Comment by microbit-matt-hillsdon** [comment]
I think I didn't translate this as it wasn't translated in V2, but I think it's worth discussion:

https://python.microbit.org/v/2?lang=fr

**Comment by microbit-matt-hillsdon** [comment]
We should localise "my program" and the comment at the top of the script.

If we can let's do it for user testing.

**Comment by microbit-matt-hillsdon** [comment]
Let's discuss the comment here (and in a new file) further. Is there any value in either of them?

**Comment by microbit-matt-hillsdon** [comment]
Short term: change to "Untitled project", make translatable.
Ensure that changing language before user edit changes text but not after.
Do this for user testing.

We don't think the comment at the start has much value. We'd like to encourage edits and reference Explore.
We should make it translatable.
@microbit-mark to suggest text for discussion.

**Comment by microbit-mark** [comment]
Some permutations in https://paper.dropbox.com/doc/Python-script-intro--BbPcjaFoaBrHPGGzuz97CepcAg-sOSEZvjTdGZRytYWq330V

I would suggest something that is explicit and related to the most common user action of editing the code/script and flashing it to the device

![image](https://user-images.githubusercontent.com/31242877/152361418-4f73a9bd-c260-4019-9f69-433f1236e502.png)

I have tried some versions where we reference the Explore menu, but I wonder if doing so might make it really confusing if you take the script out of context. Eg if I open it in a text editor and it's talking about an 'Explore' menu

![image](https://user-images.githubusercontent.com/31242877/152361713-10cf093a-07d6-428b-bbe2-0b5fed00c581.png)

**Comment by microbit-matt-hillsdon** [comment]
We should consider some kind of non-code notice/nudge too, if the main point is to communicate the above rather than to demonstrate a code comment.

**Comment by microbit-matt-hillsdon** [comment]
Moved the issue of the default script to #566 along with @microbit-mark's suggestions.

Closing this as we've addressed the project name.
