### ISSUE TITLE
`microbit` is not available as an import option to autocomplete

### ISSUE THREAD

**Issue by microbit-mark** [microbit-foundation/python-editor-next#478]
## Bug Description

Typing `from microbit import *` I would expect the `microbit` module to be available to import

## Screenshots

![image](https://user-images.githubusercontent.com/31242877/151194051-36f4fa84-d3c2-4f65-84a6-f1729192226e.png)

Chrome 97, MacOS 12

**Comment by microbit-matt-hillsdon** [comment]
This is fixed by #624 due to changes in Pyright. That explains why it was already working in VS Code (we've just merged in some three months of upstream work).

Closing.

**Comment by microbit-matt-hillsdon** [comment]
Note this is just building now on alpha: https://app.circleci.com/pipelines/github/microbit-foundation/python-editor-next/1880/workflows/ae50431f-c37f-4209-8187-656fc56a01ff
