### ISSUE TITLE
Code popup hidden by breadcrumb in some situations

### ISSUE THREAD

**Issue by microbit-robert** [microbit-foundation/python-editor-next#534]
After using search to navigate from one topic to another, the code popups for that topic appear behind the breadcrumb, but above other elements. This might be related to transform properties leftover from slide transitions.

![image](https://user-images.githubusercontent.com/95928279/152356560-011552e8-8430-4f7f-b2ca-57a85789ae94.png)

**Comment by microbit-matt-hillsdon** [comment]
@microbit-robert, can you still reproduce this?

**Comment by microbit-matt-hillsdon** [comment]
@microbit-robert, sorry, can repro now!

**Comment by microbit-matt-hillsdon** [comment]
Closed by #554.
