### ISSUE TITLE
Clicking same search result twice has no effect

### ISSUE THREAD

**Issue by microbit-robert** [microbit-foundation/python-editor-next#535]
On clicking a search result, navigation to the clicked topic entry is activated. Clicking the same search again (without clicking any other result, or navigating away from the open topic) has no effect. This is problematic if the user has scrolled through the topic, and wishes to return the searched entry using the results.

**Comment by microbit-robert** [comment]
Re-running the search and clicking on the previously clicked result **does** produce the correct navigation behaviour. E.g., search for `if`, click the `Nested if` result. Edit the search to backspace the f and retype it so a new result list is rendered. Click the `Nested if` result again and navigation works correctly.

**Comment by microbit-matt-hillsdon** [comment]
> Re-running the search and clicking on the previously clicked result **does** produce the correct navigation behaviour. E.g., search for `if`, click the `Nested if` result. Edit the search to backspace the f and retype it so a new result list is rendered. Click the `Nested if` result again and navigation works correctly.

I think I know why. The results have a navigation entry associated with them which has { anchor: id } or similar. It is the identity of that object that causes navigation to (re)occur. So we should create the object at the point of navigation from the required info, not use one from the search results. Caveat: I didn't look at the code!
