### ISSUE TITLE
Upgrade to CRA 5

### ISSUE THREAD

**Issue by microbit-matt-hillsdon** [microbit-foundation/python-editor-next#567]
Changelog: https://github.com/facebook/create-react-app/blob/main/CHANGELOG.md
Webpack 5 migration guide (hopefully mostly hidden from us by CRA): https://webpack.js.org/migrate/5/

Migration concerns:
- We use craco for the theme package. They have a prerelease version available that supports CRA 5. If it doesn't just work then we can skip it initially (branch only), hacking deployment/index.ts as required to just import the default deployment package and reverting package.json to use react-scripts.
- Web workers: the search web worker uses worker-loader. We should remove this in favour of webpack 5's built-in worker support: https://webpack.js.org/guides/web-workers/
- Check browser compatibility of the emitted code. I think it'll be browserlist driven, this is a good opportunity to make sure that makes sense.
- Compare output file structure, hashes, locations code splitting for language bundles, web worker, typeshed, etc.

Blocks #558

**Comment by microbit-robert** [comment]
Closed by #568.
