### ISSUE TITLE
Unexpected autocomplete behaviour for Image.

### ISSUE THREAD

**Issue by microbit-giles** [microbit-foundation/python-editor-next#600]
## Bug Description

I edited the default program, and started retyping a new Image name.

I was expecting to see ALL_ARROWS etc listed as autocomplete options but I got abs, accelerometer instead

## How To Reproduce

1. Go to Python editor
2. Backspace over .HEART
3. start typing

## Expected behavior

I was expecting to see ALL_ARROWS etc listed as autocomplete options

## Screenshots

![image](https://user-images.githubusercontent.com/42380137/154476886-ea4d96e1-1e29-4ed3-b1f6-98a44258ad52.png)

## Environment

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 97.0.4692.99 (Official Build) (arm64)

**Comment by microbit-matt-hillsdon** [comment]
This is https://github.com/microbit-foundation/python-editor-next/issues/265 
In general if you type this code in you should have the closing bracket inserted for you, but it's easy for folks to lose it one way or another, so we should see what we can do.

Closing as duplicate.
