### ISSUE TITLE
Minimal "Ideas" section for beta

### ISSUE THREAD

**Issue by microbit-matt-hillsdon** [microbit-foundation/python-editor-next#663]
## Depends on

Content from @microbit-giles, itself blocked on the CMS structure for this.

## Description

Content model:

- A title
- A photo-like image
- V1/V2 support tag info similar to current toolkit content
- Rich text with code blocks, generally containing a single code example

UI will use a two level design similar to Reference but the top and second levels should make good use of the image.

Top level will show only image and title.

Second level will show all content with a breadcrumb nav back to the top level.

## Todo

- [x] CMS structure
- [x] Initial content (can be dev-created)
- [x] Good enough for alpha content from @microbit-giles 
- [x] Update readme

**Comment by jaustin** [comment]
This won't be translated initially as the translation has started, but as there are a small number of strings here, perhaps we can include it in a second round?

**Comment by microbit-matt-hillsdon** [comment]
Raised #672 for Ideas search.

I'll follow up separately on plans for translation as this has missed the window for the French for beta.
