### ISSUE TITLE
Updates and impact on metrics

### ISSUE THREAD

**Issue by microbit-robert** [microbit-foundation/python-editor-next#669]
Good point raised by @microbit-carlos below. Discussion required on the best direction to take.

> Once we release V3 as beta, how often would we expect to deploy with updates?
The metrics currently create a new category based on the Editor version, so right now in alpha each category only contains a few days of data.
In a slow release schedule, like what we had with V2, that has worked fine, but maybe we want to change it in V3? As an option, we could only create a new category when we make changes to the metrics (or new UI widgets are added, which might add new metrics)?

**Comment by microbit-matt-hillsdon** [comment]
I'm tempted to just hardcode this to "Python Editor V3" for the foreseeable future.
