### ISSUE TITLE
Reference panel layout breaks when narrow with Display and Buttons categories

### ISSUE THREAD

**Issue by martinwork** [microbit-foundation/python-editor-next#707]
## Bug Description

Reference panel layout breaks when it is narrow with Display and Buttons categories.

## How To Reproduce

Steps to reproduce the behaviour:

1. Go to 'https://python.microbit.org/v/beta'
2. Make the Reference panel narrow
3. Select Display or Buttons
4. See error as in screenshot

## Expected behaviour

Works the same as other categories.

## Screenshots

![image](https://user-images.githubusercontent.com/989126/164741242-a3fe910f-cbc3-472a-a0c4-3b72c214c991.png)

## Environment

**Desktop (please complete the following information):**

- OS: [e.g. iOS] Windows 10
- Browser [e.g. chrome, safari] Chrome
- Version [e.g. 22] 100.0.4896.127

**Smartphone (please complete the following information):**

**Comment by jaustin** [comment]
Relates to #638 prehaps?

**Comment by microbit-matt-hillsdon** [comment]
Fix merged. It should be on beta in < 10 mins. You can also try it via the link on #708.
