### ISSUE TITLE
French translation: Chargement > Charger

### ISSUE THREAD

**Issue by microbit-mark** [microbit-foundation/python-editor-next#744]
Load button on the right should be an action verb in French as with other buttons. Suggest 'Charger'

<img width="795" alt="Screenshot 2022-05-12 at 11 45 56" src="https://user-images.githubusercontent.com/31242877/168053819-f90a431d-cabb-405c-88c0-91582f04ec46.png">

**Comment by microbit-matt-hillsdon** [comment]
We should review the Crowdin context for this to see if it could be clearer for the benefit of future translation in other languages.

**Comment by microbit-matt-hillsdon** [comment]
Checked with Steph and she agrees with the change.

CC @microbit-Emma for info. I'll change this directly in Crowdin.
