### ISSUE TITLE
We should use contextual links to make them accessible

### ISSUE THREAD

**Issue by microbit-mark** [microbit-foundation/python-editor-next#749]
In the Images category, the show more dropdown contains a link to '[look here](#)'. 

![image](https://user-images.githubusercontent.com/31242877/169270431-b5ba0728-6175-452b-abb5-d28e6fa0da4a.png)

This is not good for accessibility, we should make links contextual so they are easier to scan with a screen reader.

Suggest we use 

'The documentation contains a list of the [built-in images](#)'

**Comment by microbit-matt-hillsdon** [comment]
@microbit-giles might be worth fixing this shortly before the next round of translation?

**Comment by microbit-robert** [comment]
@microbit-matt-hillsdon @microbit-giles Suggest: "The API documentation contains a full list of the _built-in images_."
