### ISSUE TITLE
[Search] Clearing search box does not always clear the results

### ISSUE THREAD

**Issue by microbit-robert** [microbit-foundation/python-editor-next#754]
To recreate, type "display" in the search box and wait for the results to populate. Hold backspace to clear the search input. Search results will be shown using the starting letter, in this case "d", of the previous search term. This seems to happen invariably, but the results are misleading. If you try it with "loop", it appears to work, but this is only because there are no results for the search term "l".

![image](https://user-images.githubusercontent.com/95928279/170668493-83c0b194-be85-4ab6-bedc-3e0139195c62.png)

This does not happen if the clear "x" button is used on the right side of the search box.

**Comment by microbit-matt-hillsdon** [comment]
Good catch! Seems to be down to clearing the results outside of the debounced search function that can then be overwritten by the debounced (therefore delayed) change. Fixed on linked PR.
