### ISSUE TITLE
[Parameter help] Parameter docs only show first line

### ISSUE THREAD

**Issue by microbit-robert** [microbit-foundation/python-editor-next#760]
Parameter docs only show the first line of text, which is not necessarily the first sentence. The entire parameter doc should probably be shown for each parameter.

![image](https://user-images.githubusercontent.com/95928279/170967797-23470ddb-e859-475d-971d-c1f987a79d40.png)

**Comment by microbit-matt-hillsdon** [comment]
Now:

![image](https://user-images.githubusercontent.com/44397098/172423850-01b7a3fe-b5cf-4c41-97b2-b655f32211c6.png)
