### ISSUE TITLE
`Projects` -> `Add file` might be interpreted as "upload/load file"

### ISSUE THREAD

**Issue by microbit-carlos** [microbit-foundation/python-editor-next#761]
If a user wanted to "load" a local file (like a MicroPython accessory module) to Editor they have to go to the "Projects" section and the two buttons presented are:

<img width="478" alt="image" src="https://user-images.githubusercontent.com/29712657/170967778-6942c0b4-2920-4339-8804-84f949251b08.png">

I think some people might read the `Add file` button as "Add a file from your computer". With that in mind I think something like `Add new file` or `Create file`/`Create new file` might be a bit more clear.

**Comment by microbit-matt-hillsdon** [comment]
Personally I find both "Create file" or "Create new file" clearer. However, we changed it from "Create new file" to avoid the misconception seen in the first round of user testing that users were creating a new project. Before changing it back (more or less) we should consider this scenario. Does the Projects tab give sufficient context to prevent the confusion?

The original change was made on #664 along with Files -> Project and using the project name as the Project tab header.

**Comment by microbit-carlos** [comment]
Yeah, I could see how `Create new file` could maybe misinterpreted by somebody looking for a way to create a new project.

In that case I think maybe `Create file` hits a better middle ground, without the word "new" is less likely to be interpreted as "new project".

**Comment by microbit-matt-hillsdon** [comment]
I had a support interaction today where "Add file" was misunderstood in this way. I think we should go ahead and make this change (and soon, so it's in place for translation).
