### ISSUE TITLE
Allow module developers to specify that modules should be hard to edit/not editable

### ISSUE THREAD

**Issue by jaustin** [microbit-foundation/python-editor-next#765]
Third parties:

- Parallax

## Description

When distributing module files, eg for accessories like the cyber:bot, it's helpful to mark that the module should not be edited without careful thought.

In the V2 editor it wasn't actually possible to edit the files, so we could be introducing a new class of bug where students accidentally change modules that are really providing baked in functionality. 

## Todo

- [x] Choose the approach for limiting module editablility
    - We considered a per session (potentially per module) setting but liked the additional friction of going via settings.
    - We considered adding n additional warning dialog but wanted to see whether there was an issue in practice.
- [x] Design it
- [x] Implement it.

**Comment by microbit-matt-hillsdon** [comment]
This is live with an editor overlay and a setting to disable.

#848 will add a little more context to the setting.

![image](https://user-images.githubusercontent.com/44397098/180749912-b004bcc9-71cc-48b0-84dc-dc530ed71f84.png)

![image](https://user-images.githubusercontent.com/44397098/180749944-18af9dc2-e862-4bdb-8b3e-0c6761a1c9e3.png)

**Comment by microbit-matt-hillsdon** [comment]
Closed by https://github.com/microbit-foundation/python-editor-next/pull/815
