### ISSUE TITLE
Side menu alignment after drag on iPad chrome browser

### ISSUE THREAD

**Issue by microbit-lucy** [microbit-foundation/python-editor-next#781]
## Bug Description

When you drag a code snippet from the menu on the left, as it is moved into the code editor area the menu on the left shifts sideways so that some of the text is hidden under the bar on the left. 

## How To Reproduce

1. Open https://python.microbit.org/v/beta in Chrome on iPad
2. Drag a code snippet into the code editor area
3. Look at Reference menu 

## Expected behavior

Alignment of menu is unchanged

## Screenshots

![IMG_293B8DD0E5F6-1](https://user-images.githubusercontent.com/102724242/175517647-f62c431b-7beb-4771-ad7a-24a60bd44a09.jpeg)

https://user-images.githubusercontent.com/102724242/175518012-6f6cc0e1-83b8-415d-9359-2c2b9b24bd5f.MP4

## Environment

**Desktop (please complete the following information):**

- OS: iPad
- Browser: Chrome
- Version ??

**Smartphone (please complete the following information):**

- Device: iPad Air 3rd Gen
- OS: 15.4.1
- Browser Chrome
- Version ?

**Comment by microbit-matt-hillsdon** [comment]
I can repro this in Safari 15 on iOS. I don't think it happened in Safari 15 on iOS (which uses the same rendering engine as Chrome on iOS) before the changes on #777 went in yesterday. I'll check this. Either way we may need to work around it.
