### ISSUE TITLE
SoundEvent API descriptions seem reversed

### ISSUE THREAD

**Issue by martinwork** [microbit-foundation/python-editor-next#864]
## Bug Description

These descriptions seem reversed

![image](https://user-images.githubusercontent.com/989126/183058891-c2aef808-a6b0-4327-a913-55b83f760b7e.png)

**Comment by microbit-matt-hillsdon** [comment]
Thanks, good catch. I'll fix these later today along with the spi feedback.

**Comment by microbit-matt-hillsdon** [comment]
Fixed in main branch. Redeploying to the beta now (~10 mins).

I'll update the API documentation in Crowdin at ~5pm.

**Comment by martinwork** [comment]
`Thanks Matt!

**Comment by microbit-matt-hillsdon** [comment]
Updated in Crowdin.
