### ISSUE TITLE
Simulator terminal error is not cleared.

### ISSUE THREAD

**Issue by microbit-robert** [microbit-foundation/python-editor-next#869]
To reproduce:

- Run simulator with no code. 
- Create error, e.g., use undefined variable.
- Run simulator and see error output in simulator terminal.
- Clear error in code.
- Re-run simulator and see that error output is not cleared.

**Comment by microbit-matt-hillsdon** [comment]
We need to emit EVENT_SERIAL_RESET before a flash in the simulator device connection.

This matches the real device (which stops listening too, which we don't really need to do).
