### ISSUE TITLE
[Simulator] Sometimes can't scroll the simulator modules area

### ISSUE THREAD

**Issue by microbit-matt-hillsdon** [microbit-foundation/python-editor-next#872]
![image](https://user-images.githubusercontent.com/44397098/183689288-3fe8fb9e-7759-4fac-9bba-afec63b63856.png)

There's a Temperature sensor down there somewhere but I can't scroll.

This is on Windows so there really should be scrollbars.

**Comment by microbit-robert** [comment]
I've not managed to reproduce this yet, is there a consistent way to get into this state?

**Comment by microbit-matt-hillsdon** [comment]
Repro:

1. Resize window so bottom area of sim must scroll
1. Open https://python.microbit.org/v/beta?flag=simulator
1. Hide simulator
1. Show simulator
1. Scroll is broken
