### ISSUE TITLE
Gutter width does not increase with font size.

### ISSUE THREAD

**Issue by microbit-robert** [microbit-foundation/python-editor-next#877]
The gutter width does not increase with font size which causes gutter markers to be truncated at font sizes of 20 or more.

![image](https://user-images.githubusercontent.com/95928279/184108066-51b065b8-fbb0-4c5b-acd9-c85e4259408f.png)

**Comment by microbit-matt-hillsdon** [comment]
Lint markers have 1em width height.
Width is 1.8rem = 28.8px 
Font size is, somewhat improbably, 16pt.
So I make that 1.35em for an equivalent gutter width.

Need to find .cm-gutter.cm-gutter-lint in the theme.
