### ISSUE TITLE
[Data logging] Default in API docs for log.set_labels timestamp parameter should be SECONDS not MILLISECONDS

### ISSUE THREAD

**Issue by microbit-matt-hillsdon** [microbit-foundation/python-editor-next#920]
Spotted by Rob reviewing the simulator work.

The default for the log.set_labels timestamp parameter should be SECONDS not MILLISECONDS.

The behaviour is correct, just the docs/stubs that are misleading.

**Comment by microbit-matt-hillsdon** [comment]
Note docs for data logging aren't merged at the time of writing - see https://github.com/bbcmicrobit/micropython/pull/720 (this may change soon).

**Comment by microbit-robert** [comment]
Our example for `log.set_labels` should use a keyword argument to set the timestamp. See example and conflicting docs below:

![image](https://user-images.githubusercontent.com/95928279/187451247-081b9890-c73f-4b55-b0c0-735d69091f0c.png)
