### ISSUE TITLE
Warning due to recent lunr changes

### ISSUE THREAD

**Issue by microbit-matt-hillsdon** [microbit-foundation/python-editor-next#949]
Can we do something about this?

![image](https://user-images.githubusercontent.com/44397098/189391439-d27e8c14-7b3b-4839-aa64-4f48746b5797.png)

Presumably due to #943

**Comment by microbit-robert** [comment]
I don't think we can prevent the overwriting of an "existing registered function", but we can overwrite the lunr warn function to do nothing, which I'm not convinced is a great idea.
